-- Batch 3: Design & UX (3) + Education (3) + Product Management (3) + Research (3) = 12 prompts
INSERT INTO public.prompts (
  slug,
  title,
  description,
  category_id,
  category_name,
  category_slug,
  prompt,
  tags,
  recommended_model,
  model_icon,
  use_cases,
  example_output,
  output_screenshots,
  "references",
  variables,
  tips,
  difficulty,
  saves_count,
  is_published,
  created_at
) VALUES
-- 1. design-system-creator
(
  'design-system-creator',
  'Design System Creator',
  'Build a comprehensive design system with tokens, components, patterns, and documentation.',
  'd692fdf0-cdb7-416f-968d-0800b4b1583f',
  'Design & UX',
  'design-ux',
  E'You are a design systems architect. Create a design system specification.\n\n**Brand:** {{brand}}\n**Platform:** {{platform}}\n**Existing brand colors:** {{colors}}\n**Target feel:** {{feel}}\n\nDeliver:\n\n1. **Design Tokens**\n   - Color palette (primary, secondary, neutral, semantic)\n   - Typography scale (sizes, weights, line heights)\n   - Spacing scale (4px base grid)\n   - Border radius values\n   - Shadow definitions\n   - Animation/transition values\n\n2. **Component Library** (specifications for)\n   - Button (variants, sizes, states)\n   - Input fields (types, validation states)\n   - Card (layouts, variants)\n   - Modal/Dialog\n   - Navigation\n   - Table\n   - Toast/Notification\n\n3. **Patterns**\n   - Form layouts\n   - Error handling\n   - Loading states\n   - Empty states\n   - Responsive breakpoints\n\n4. **Accessibility**\n   - Color contrast ratios\n   - Focus states\n   - Screen reader considerations\n   - Keyboard navigation\n\nProvide CSS custom properties and Tailwind config.',
  ARRAY['design-system', 'ui', 'components', 'accessibility'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Starting a design system', 'Standardizing UI components', 'Improving design consistency'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"brand","description":"Brand name and identity"},{"name":"platform","description":"Web, mobile, both"},{"name":"colors","description":"Existing brand colors if any"},{"name":"feel","description":"Modern, playful, corporate, minimal"}]'::jsonb,
  NULL,
  'Advanced',
  267,
  true,
  '2025-01-16'::timestamptz
),
-- 2. ux-audit-framework
(
  'ux-audit-framework',
  'UX Audit Framework',
  'Conduct a thorough UX audit identifying usability issues, accessibility gaps, and improvement opportunities.',
  'd692fdf0-cdb7-416f-968d-0800b4b1583f',
  'Design & UX',
  'design-ux',
  E'You are a senior UX researcher and designer. Conduct a comprehensive UX audit.\n\n**Product/Website:** {{product}}\n**Target Users:** {{users}}\n**Key User Flows:** {{flows}}\n**Known Pain Points:** {{pain_points}}\n\nAudit Framework:\n\n1. **Heuristic Evaluation** (Nielsen''s 10 heuristics)\n   - Score each heuristic 1-5\n   - Specific violations found\n   - Severity rating\n\n2. **User Flow Analysis**\n   - Steps to complete key tasks\n   - Friction points identified\n   - Drop-off risk areas\n   - Simplification recommendations\n\n3. **Visual Design Review**\n   - Consistency issues\n   - Information hierarchy\n   - White space usage\n   - Typography readability\n\n4. **Accessibility Audit**\n   - WCAG 2.1 AA compliance\n   - Keyboard navigation\n   - Screen reader compatibility\n   - Color contrast issues\n\n5. **Recommendations**\n   - Quick wins (low effort, high impact)\n   - Medium-term improvements\n   - Strategic redesign areas\n   - Priority matrix (Impact vs Effort)',
  ARRAY['ux-audit', 'usability', 'accessibility', 'user-research'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Improving existing products', 'Pre-redesign assessment', 'Accessibility compliance'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"product","description":"Product or website to audit"},{"name":"users","description":"Primary user personas"},{"name":"flows","description":"Critical user journeys"},{"name":"pain_points","description":"Known user complaints"}]'::jsonb,
  NULL,
  'Advanced',
  178,
  true,
  '2025-02-04'::timestamptz
),
-- 3. responsive-layout-generator
(
  'responsive-layout-generator',
  'Responsive Layout Generator',
  'Generate responsive CSS/Tailwind layouts with mobile-first approach and proper breakpoints.',
  'd692fdf0-cdb7-416f-968d-0800b4b1583f',
  'Design & UX',
  'design-ux',
  E'You are a frontend specialist focusing on responsive design. Create a responsive layout.\n\n**Layout description:** {{layout}}\n**Framework:** {{framework}}\n**Breakpoints needed:** {{breakpoints}}\n**Content types:** {{content}}\n\nProvide:\n\n1. **Mobile Layout** (320px-768px)\n   - Single column structure\n   - Touch-friendly spacing\n   - Collapsible navigation\n\n2. **Tablet Layout** (768px-1024px)\n   - Adapted grid\n   - Sidebar behavior\n\n3. **Desktop Layout** (1024px+)\n   - Full grid implementation\n   - Hover states\n   - Fixed elements\n\n4. **Code** (HTML + CSS/Tailwind)\n   - Semantic HTML structure\n   - Complete responsive styles\n   - Container queries if applicable\n   - CSS Grid + Flexbox combination\n\n5. **Testing Checklist**\n   - Key breakpoints to verify\n   - Common device sizes\n   - Landscape orientation handling',
  ARRAY['responsive', 'css', 'tailwind', 'layout', 'mobile-first'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Building responsive pages', 'Converting designs to code', 'Mobile optimization'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"layout","description":"Describe the layout structure"},{"name":"framework","description":"Tailwind, plain CSS, Bootstrap"},{"name":"breakpoints","description":"Mobile, tablet, desktop, widescreen"},{"name":"content","description":"Text, images, cards, tables, forms"}]'::jsonb,
  NULL,
  'Intermediate',
  145,
  true,
  '2025-02-09'::timestamptz
),
-- 4. lesson-plan-creator
(
  'lesson-plan-creator',
  'Interactive Lesson Plan Creator',
  'Design engaging lesson plans with learning objectives, activities, assessments, and differentiation strategies.',
  'c3592870-3a54-4562-a73a-458a21e21a7d',
  'Education',
  'education',
  E'You are an experienced instructional designer. Create a comprehensive lesson plan.\n\n**Subject:** {{subject}}\n**Topic:** {{topic}}\n**Grade/Level:** {{level}}\n**Duration:** {{duration}}\n**Learning Style Focus:** {{style}}\n\nDeliver:\n\n1. **Learning Objectives** (3-5, using Bloom''s Taxonomy)\n   - Knowledge, Comprehension, Application, Analysis, Synthesis, Evaluation\n\n2. **Lesson Structure**\n   - Hook/Warm-up (5 min)\n   - Direct instruction (15 min)\n   - Guided practice (15 min)\n   - Independent practice (10 min)\n   - Closure/Assessment (5 min)\n\n3. **Activities**\n   - Main activity with step-by-step instructions\n   - Alternative activity for different learning styles\n   - Extension activity for advanced learners\n\n4. **Assessment**\n   - Formative assessment questions\n   - Exit ticket\n   - Rubric for main activity\n\n5. **Differentiation**\n   - Scaffolding for struggling learners\n   - Extensions for advanced learners\n   - ELL modifications\n\n6. **Materials & Resources** needed',
  ARRAY['lesson-plan', 'teaching', 'curriculum', 'education'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Creating lesson plans', 'Curriculum development', 'Training program design'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"subject","description":"Subject area"},{"name":"topic","description":"Specific topic"},{"name":"level","description":"Grade level or audience level"},{"name":"duration","description":"Class duration"},{"name":"style","description":"Visual, auditory, kinesthetic, mixed"}]'::jsonb,
  NULL,
  'Intermediate',
  189,
  true,
  '2025-01-19'::timestamptz
),
-- 5. socratic-tutor
(
  'socratic-tutor',
  'Socratic Method Tutor',
  'Learn any concept through guided questioning that builds deep understanding instead of memorization.',
  'c3592870-3a54-4562-a73a-458a21e21a7d',
  'Education',
  'education',
  E'You are a Socratic tutor. Your role is to help me deeply understand a concept through questioning, NOT by giving direct answers.\n\n**Subject:** {{subject}}\n**Topic I want to learn:** {{topic}}\n**My current understanding:** {{current_level}}\n\nRules:\n1. NEVER give the answer directly\n2. Ask ONE question at a time\n3. Start with what I already know\n4. Guide me to discover the answer myself\n5. If I''m stuck, give a small hint, not the answer\n6. Celebrate when I make connections\n7. Build complexity gradually\n8. Connect new concepts to things I already understand\n9. Use analogies and real-world examples\n10. After I understand, ask me to explain it back in my own words\n\nStart by asking me what I already know about {{topic}}, then guide me from there. If I give an incorrect answer, don''t say "wrong" \u2014 instead, ask a question that reveals the flaw in my reasoning.',
  ARRAY['socratic-method', 'tutoring', 'learning', 'critical-thinking'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Deep learning of new concepts', 'Preparing for exams', 'Building critical thinking skills'],
  NULL,
  NULL,
  '[{"title":"Socratic Method in AI Tutoring","url":"https://en.wikipedia.org/wiki/Socratic_method"}]'::jsonb,
  '[{"name":"subject","description":"The subject area"},{"name":"topic","description":"The specific topic to learn"},{"name":"current_level","description":"What you already know"}]'::jsonb,
  NULL,
  'Beginner',
  445,
  true,
  '2025-01-08'::timestamptz
),
-- 6. concept-explainer
(
  'concept-explainer',
  'Multi-Level Concept Explainer',
  'Understand any concept explained at multiple levels of complexity, from ELI5 to expert.',
  'c3592870-3a54-4562-a73a-458a21e21a7d',
  'Education',
  'education',
  E'Explain the following concept at multiple levels of complexity.\n\n**Concept:** {{concept}}\n**Field:** {{field}}\n\nProvide explanations at these levels:\n\n1. **ELI5 (Explain Like I''m 5)** - Simple analogy, no jargon\n2. **High School Student** - Basic technical terms, real-world examples\n3. **College Student** - Formal definitions, theoretical framework\n4. **Professional** - Industry context, practical applications, trade-offs\n5. **Expert** - Cutting-edge developments, open problems, research frontiers\n\nFor each level:\n- Use an appropriate analogy\n- Include a concrete example\n- Highlight what''s new at this level vs. the previous one\n\nEnd with:\n- Common misconceptions about this concept\n- How it connects to 3 related concepts\n- Resources for further learning at each level',
  ARRAY['explanation', 'learning', 'teaching', 'concepts'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Learning new concepts', 'Teaching at different levels', 'Content creation'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"concept","description":"The concept to explain"},{"name":"field","description":"The field or domain"}]'::jsonb,
  NULL,
  'Beginner',
  356,
  true,
  '2025-01-11'::timestamptz
),
-- 7. prd-generator
(
  'prd-generator',
  'Product Requirements Document (PRD)',
  'Generate comprehensive PRDs with user stories, acceptance criteria, technical requirements, and success metrics.',
  '80772e43-ede5-4243-b126-45f6784d9615',
  'Product Management',
  'product-management',
  E'You are a senior product manager at a top tech company. Write a comprehensive PRD.\n\n**Feature/Product:** {{feature}}\n**Problem Statement:** {{problem}}\n**Target Users:** {{users}}\n**Business Context:** {{context}}\n\nProduce:\n\n1. **Overview**\n   - Problem statement\n   - Proposed solution\n   - Success metrics (SMART goals)\n   - Non-goals (explicitly out of scope)\n\n2. **User Stories** (5-10)\n   - As a [user type], I want [action] so that [benefit]\n   - Acceptance criteria for each (Given/When/Then)\n   - Priority: P0/P1/P2\n\n3. **Functional Requirements**\n   - Detailed feature specifications\n   - User flows with decision points\n   - Edge cases and error states\n\n4. **Technical Requirements**\n   - Architecture considerations\n   - API requirements\n   - Data model changes\n   - Performance requirements\n   - Security requirements\n\n5. **Design Requirements**\n   - Wireframe descriptions\n   - Key screens and states\n   - Accessibility requirements\n\n6. **Launch Plan**\n   - Feature flag strategy\n   - Rollout phases\n   - Rollback plan\n   - Monitoring and alerts',
  ARRAY['prd', 'product-management', 'requirements', 'user-stories'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Writing product specs', 'Feature planning', 'Stakeholder alignment'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"feature","description":"Feature or product name"},{"name":"problem","description":"What problem does this solve"},{"name":"users","description":"Who benefits from this"},{"name":"context","description":"Business goals, constraints, timeline"}]'::jsonb,
  NULL,
  'Intermediate',
  389,
  true,
  '2025-01-13'::timestamptz
),
-- 8. user-interview-script
(
  'user-interview-script',
  'User Interview Script Generator',
  'Create structured user interview scripts that uncover real insights without leading questions.',
  '80772e43-ede5-4243-b126-45f6784d9615',
  'Product Management',
  'product-management',
  E'You are a UX researcher expert in qualitative research methods. Create an interview script.\n\n**Research Goal:** {{goal}}\n**Target Users:** {{users}}\n**Product Area:** {{product}}\n**Interview Duration:** {{duration}}\n\nCreate:\n\n1. **Introduction Script** (2 min)\n   - Warm-up and rapport building\n   - Consent and recording permission\n   - Set expectations\n\n2. **Warm-up Questions** (3 min)\n   - Background and context\n   - Current workflow\n\n3. **Core Questions** (20 min)\n   - 8-10 open-ended questions\n   - Follow-up probes for each\n   - "Tell me about a time..." prompts\n   - Avoid leading questions\n\n4. **Concept Testing** (if applicable, 10 min)\n   - Task scenarios\n   - Think-aloud prompts\n   - Satisfaction scale questions\n\n5. **Wrap-up** (5 min)\n   - Summary and clarification\n   - "Anything else?" prompt\n   - Thank you and next steps\n\nInclude:\n- Questions to AVOID (with explanations why)\n- Note-taking template\n- Analysis framework for synthesizing results',
  ARRAY['user-research', 'interviews', 'qualitative', 'ux-research'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Conducting user research', 'Product discovery', 'Validating assumptions'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"goal","description":"What you want to learn"},{"name":"users","description":"Who you''re interviewing"},{"name":"product","description":"Product or feature area"},{"name":"duration","description":"Interview length"}]'::jsonb,
  NULL,
  'Intermediate',
  167,
  true,
  '2025-02-11'::timestamptz
),
-- 9. feature-prioritization
(
  'feature-prioritization',
  'Feature Prioritization Framework',
  'Prioritize features using RICE, MoSCoW, and impact-effort matrices with stakeholder alignment.',
  '80772e43-ede5-4243-b126-45f6784d9615',
  'Product Management',
  'product-management',
  E'You are a product strategy consultant. Help prioritize the following features.\n\n**Product:** {{product}}\n**Features to prioritize:**\n{{features}}\n\n**Business goals:** {{goals}}\n**Team capacity:** {{capacity}}\n**Timeline:** {{timeline}}\n\nApply these frameworks:\n\n1. **RICE Score** for each feature:\n   - Reach: How many users affected per quarter\n   - Impact: How much it moves the needle (0.25-3x)\n   - Confidence: How sure are we (0-100%)\n   - Effort: Person-months needed\n   - Final RICE = (R \u00d7 I \u00d7 C) / E\n\n2. **MoSCoW Classification**\n   - Must have / Should have / Could have / Won''t have\n\n3. **Impact-Effort Matrix**\n   - Plot each feature\n   - Identify quick wins, big bets, fill-ins, time sinks\n\n4. **Recommendation**\n   - Prioritized roadmap for the timeline\n   - Dependencies between features\n   - What to cut and why\n   - Risks of each ordering',
  ARRAY['prioritization', 'roadmap', 'rice', 'product-strategy'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Quarterly planning', 'Roadmap creation', 'Stakeholder discussions'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"product","description":"Product name"},{"name":"features","description":"List of features to prioritize"},{"name":"goals","description":"Business objectives"},{"name":"capacity","description":"Team size and availability"},{"name":"timeline","description":"Planning horizon"}]'::jsonb,
  NULL,
  'Intermediate',
  234,
  true,
  '2025-01-26'::timestamptz
),
-- 10. literature-review-assistant
(
  'literature-review-assistant',
  'Literature Review Assistant',
  'Conduct structured literature reviews with synthesis, gap analysis, and research direction suggestions.',
  '746f28af-325c-4ccc-8604-6a5252ec8643',
  'Research',
  'research',
  E'You are an academic research assistant. Help me conduct a literature review.\n\n**Research Topic:** {{topic}}\n**Field:** {{field}}\n**Scope:** {{scope}}\n**Known papers/sources:** {{known_sources}}\n\nProvide:\n\n1. **Research Landscape Overview**\n   - Key themes and sub-topics\n   - Major schools of thought\n   - Timeline of development\n\n2. **Key Findings Synthesis**\n   - Common findings across studies\n   - Conflicting findings and why\n   - Methodological approaches used\n\n3. **Gap Analysis**\n   - What hasn''t been studied\n   - Methodological gaps\n   - Population/context gaps\n\n4. **Critical Analysis Framework**\n   - Strengths of existing research\n   - Limitations and biases\n   - Quality assessment criteria\n\n5. **Research Directions**\n   - Promising future research questions\n   - Methodological suggestions\n   - Interdisciplinary opportunities\n\n6. **Citation Organization**\n   - Suggested categories for organizing sources\n   - Key authors to follow\n   - Recommended search queries for databases',
  ARRAY['literature-review', 'academic', 'research', 'synthesis'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Academic research', 'Thesis writing', 'Research proposals'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"topic","description":"Research topic"},{"name":"field","description":"Academic field"},{"name":"scope","description":"Time range, geographic focus"},{"name":"known_sources","description":"Papers you''ve already found"}]'::jsonb,
  NULL,
  'Advanced',
  234,
  true,
  '2025-01-17'::timestamptz
),
-- 11. research-paper-analyzer
(
  'research-paper-analyzer',
  'Research Paper Analyzer',
  'Analyze research papers critically, evaluating methodology, findings, and implications.',
  '746f28af-325c-4ccc-8604-6a5252ec8643',
  'Research',
  'research',
  E'You are a critical research analyst. Analyze this research paper/study.\n\n**Paper/Study:** {{paper_details}}\n**Field:** {{field}}\n**Your goal:** {{goal}}\n\nProvide:\n\n1. **Summary**\n   - Research question\n   - Methodology\n   - Key findings\n   - Conclusions\n\n2. **Methodology Critique**\n   - Sample size adequacy\n   - Control group design\n   - Potential confounding variables\n   - Statistical methods appropriateness\n   - Reproducibility assessment\n\n3. **Findings Analysis**\n   - Effect sizes and practical significance\n   - Statistical vs practical significance\n   - Generalizability of results\n   - Alternative interpretations\n\n4. **Bias Assessment**\n   - Selection bias\n   - Publication bias\n   - Funding source bias\n   - Confirmation bias indicators\n\n5. **Implications**\n   - For the field\n   - For practice/policy\n   - For future research\n\n6. **Quality Score** (1-10) with justification',
  ARRAY['research-analysis', 'critical-thinking', 'methodology', 'academic'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Evaluating research papers', 'Journal club preparation', 'Evidence-based decision making'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"paper_details","description":"Paper title, abstract, or key details"},{"name":"field","description":"Research field"},{"name":"goal","description":"Why you''re analyzing this paper"}]'::jsonb,
  NULL,
  'Advanced',
  178,
  true,
  '2025-02-01'::timestamptz
),
-- 12. competitive-analysis
(
  'competitive-analysis',
  'Competitive Analysis Framework',
  'Conduct thorough competitive analysis with market positioning, feature comparison, and strategic recommendations.',
  '746f28af-325c-4ccc-8604-6a5252ec8643',
  'Research',
  'research',
  E'You are a strategy consultant. Conduct a competitive analysis.\n\n**Your Product/Company:** {{company}}\n**Industry:** {{industry}}\n**Key Competitors:** {{competitors}}\n**Analysis Goal:** {{goal}}\n\nDeliver:\n\n1. **Market Overview**\n   - Market size and growth\n   - Key trends\n   - Regulatory factors\n\n2. **Competitor Profiles** (for each)\n   - Value proposition\n   - Target market\n   - Pricing model\n   - Strengths and weaknesses\n   - Recent moves/announcements\n\n3. **Feature Comparison Matrix**\n   - Key features side by side\n   - Scoring (1-5) per feature\n   - Gaps and opportunities\n\n4. **Positioning Map**\n   - 2x2 matrix (suggest best axes)\n   - Where each competitor sits\n   - White space opportunities\n\n5. **Strategic Recommendations**\n   - Differentiation opportunities\n   - Features to build\n   - Markets to enter/avoid\n   - Pricing strategy suggestions\n   - Partnership opportunities\n\n6. **Monitoring Plan**\n   - What to track\n   - How often\n   - Alert triggers',
  ARRAY['competitive-analysis', 'market-research', 'strategy', 'business'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Strategic planning', 'Market entry decisions', 'Product positioning'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"company","description":"Your company/product"},{"name":"industry","description":"Industry or market"},{"name":"competitors","description":"List of competitors to analyze"},{"name":"goal","description":"What decision this analysis supports"}]'::jsonb,
  NULL,
  'Intermediate',
  267,
  true,
  '2025-01-24'::timestamptz
);
