-- Batch 2: Data Science & Analysis (4 prompts) + Marketing (4 prompts) = 8 prompts
INSERT INTO public.prompts (
  slug,
  title,
  description,
  category_id,
  category_name,
  category_slug,
  prompt,
  tags,
  recommended_model,
  model_icon,
  use_cases,
  example_output,
  output_screenshots,
  "references",
  variables,
  tips,
  difficulty,
  saves_count,
  is_published,
  created_at
) VALUES
-- 1. data-analysis-pipeline
(
  'data-analysis-pipeline',
  'Data Analysis Pipeline Builder',
  'Build complete data analysis pipelines with cleaning, exploration, visualization, and insights extraction.',
  'a5260b2a-bfb0-4abb-aa45-7aa4511250de',
  'Data Science & Analysis',
  'data-science',
  E'You are a senior data scientist. Build a complete analysis pipeline for the following dataset.\n\n**Dataset description:** {{dataset}}\n**Columns/Fields:** {{columns}}\n**Business question:** {{question}}\n**Tools:** {{tools}}\n\nProvide a complete pipeline:\n\n1. **Data Loading & Inspection**\n   - Code to load and inspect the data\n   - Data types, shape, memory usage\n\n2. **Data Cleaning**\n   - Missing value strategy\n   - Outlier detection and handling\n   - Data type conversions\n   - Deduplication\n\n3. **Exploratory Data Analysis**\n   - Summary statistics\n   - Distribution analysis\n   - Correlation analysis\n   - 5+ visualization code snippets (matplotlib/plotly)\n\n4. **Feature Engineering**\n   - New features to create\n   - Encoding strategies\n   - Scaling/normalization\n\n5. **Analysis & Insights**\n   - Statistical tests if applicable\n   - Key findings (3-5 insights)\n   - Recommendations based on data\n\n6. **Presentation-Ready Output**\n   - Executive summary (3 bullet points)\n   - Key chart descriptions\n   - Next steps',
  ARRAY['data-analysis', 'python', 'pandas', 'visualization'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Analyzing business datasets', 'Creating data reports', 'Exploratory data analysis'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"dataset","description":"What the data represents"},{"name":"columns","description":"List of columns and their meaning"},{"name":"question","description":"What business question to answer"},{"name":"tools","description":"Python/Pandas, R, SQL, etc."}]'::jsonb,
  NULL,
  'Intermediate',
  278,
  true,
  '2025-01-22'::timestamptz
),
-- 2. sql-query-optimizer
(
  'sql-query-optimizer',
  'SQL Query Optimizer',
  'Optimize slow SQL queries with explain plan analysis, indexing suggestions, and rewrite recommendations.',
  'a5260b2a-bfb0-4abb-aa45-7aa4511250de',
  'Data Science & Analysis',
  'data-science',
  E'You are a database performance specialist. Optimize the following SQL query.\n\n**Query:**\n```sql\n{{query}}\n```\n\n**Database:** {{database}}\n**Table sizes:** {{table_sizes}}\n**Current execution time:** {{execution_time}}\n**Existing indexes:** {{indexes}}\n\nProvide:\n\n1. **Query Analysis** - What the query does step by step\n2. **Performance Bottlenecks** - Why it''s slow\n3. **Optimized Query** - Rewritten for performance\n4. **Index Recommendations** - What indexes to add/modify\n5. **Explain Plan Interpretation** - How to read the execution plan\n6. **Alternative Approaches** - CTEs, materialized views, denormalization\n7. **Estimated Improvement** - Expected speedup factor',
  ARRAY['sql', 'database', 'performance', 'optimization'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Optimizing slow database queries', 'Database performance tuning', 'Learning query optimization'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"query","description":"The SQL query to optimize"},{"name":"database","description":"PostgreSQL, MySQL, SQLite, etc."},{"name":"table_sizes","description":"Approximate row counts"},{"name":"execution_time","description":"Current query time"},{"name":"indexes","description":"Existing indexes on relevant tables"}]'::jsonb,
  NULL,
  'Advanced',
  187,
  true,
  '2025-02-03'::timestamptz
),
-- 3. ml-model-selector
(
  'ml-model-selector',
  'ML Model Selection Advisor',
  'Get expert guidance on choosing the right machine learning model for your specific problem and dataset.',
  'a5260b2a-bfb0-4abb-aa45-7aa4511250de',
  'Data Science & Analysis',
  'data-science',
  E'You are a machine learning expert. Help me select the right model for my problem.\n\n**Problem type:** {{problem_type}}\n**Dataset size:** {{dataset_size}}\n**Features:** {{features}}\n**Target variable:** {{target}}\n**Constraints:** {{constraints}}\n\nProvide:\n\n1. **Problem Classification** - Supervised/unsupervised, regression/classification\n2. **Top 3 Model Recommendations** ranked by suitability:\n   - Model name and brief description\n   - Pros and cons for this specific problem\n   - Expected performance range\n   - Training time and resource requirements\n\n3. **Implementation Plan** for the top choice:\n   - Data preprocessing steps\n   - Hyperparameter tuning strategy\n   - Cross-validation approach\n   - Evaluation metrics to use\n\n4. **Code Template** - Sklearn/PyTorch/TensorFlow starter code\n5. **Common Pitfalls** to avoid for this problem type',
  ARRAY['machine-learning', 'model-selection', 'scikit-learn', 'deep-learning'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Choosing ML algorithms', 'Starting new ML projects', 'Comparing model approaches'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"problem_type","description":"Classification, regression, clustering, etc."},{"name":"dataset_size","description":"Number of samples and features"},{"name":"features","description":"Types of input features"},{"name":"target","description":"What you''re predicting"},{"name":"constraints","description":"Latency, interpretability, compute budget"}]'::jsonb,
  NULL,
  'Advanced',
  203,
  true,
  '2025-01-28'::timestamptz
),
-- 4. dashboard-kpi-designer
(
  'dashboard-kpi-designer',
  'Dashboard & KPI Designer',
  'Design data dashboards with the right KPIs, visualizations, and layout for maximum impact.',
  'a5260b2a-bfb0-4abb-aa45-7aa4511250de',
  'Data Science & Analysis',
  'data-science',
  E'You are a business intelligence specialist. Design a dashboard for the following.\n\n**Business area:** {{business_area}}\n**Stakeholders:** {{stakeholders}}\n**Key decisions to support:** {{decisions}}\n**Data available:** {{data_sources}}\n\nDeliver:\n\n1. **KPI Selection** (5-8 metrics)\n   - Metric name and formula\n   - Why it matters\n   - Target/benchmark\n   - Update frequency\n\n2. **Dashboard Layout**\n   - Section organization\n   - Chart type for each metric (and why)\n   - Filter and drill-down options\n   - Mobile responsiveness notes\n\n3. **Visual Design**\n   - Color coding strategy\n   - Alert thresholds\n   - Comparison views (period over period)\n\n4. **Implementation**\n   - SQL queries for each KPI\n   - Recommended tool (Tableau, Looker, Metabase)\n   - Refresh schedule',
  ARRAY['dashboard', 'kpi', 'business-intelligence', 'visualization'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Building executive dashboards', 'KPI definition', 'BI tool setup'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"business_area","description":"Sales, marketing, product, finance"},{"name":"stakeholders","description":"Who will use this dashboard"},{"name":"decisions","description":"What decisions should this inform"},{"name":"data_sources","description":"Available data tables/sources"}]'::jsonb,
  NULL,
  'Intermediate',
  167,
  true,
  '2025-02-07'::timestamptz
),
-- 5. product-launch-campaign
(
  'product-launch-campaign',
  'Product Launch Campaign Planner',
  'Plan a complete product launch campaign with messaging, channels, timeline, and content strategy.',
  '90bbde45-1b2e-498e-8336-268e4fe15bb1',
  'Marketing',
  'marketing',
  E'You are a growth marketing strategist planning a product launch. Create a comprehensive launch plan.\n\n**Product:** {{product}}\n**Target Market:** {{market}}\n**Launch Date:** {{date}}\n**Budget:** {{budget}}\n**Unique Value Proposition:** {{uvp}}\n\nDeliver:\n\n1. **Launch Strategy**\n   - Pre-launch (4 weeks before)\n   - Launch week\n   - Post-launch (4 weeks after)\n\n2. **Messaging Framework**\n   - Hero message (one sentence)\n   - Supporting messages (3 pillars)\n   - Objection handling scripts\n   - Social proof strategy\n\n3. **Channel Plan**\n   - Organic channels with content calendar\n   - Paid channels with budget allocation\n   - PR and influencer outreach\n   - Email sequence (5 emails)\n\n4. **Content Deliverables**\n   - Landing page copy\n   - Launch announcement\n   - Social media posts (5 per platform)\n   - Press release outline\n\n5. **Metrics & Goals**\n   - KPIs for each channel\n   - Week-by-week targets\n   - A/B test plan',
  ARRAY['product-launch', 'campaign', 'growth', 'strategy'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Launching new products', 'Go-to-market strategy', 'Campaign planning'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"product","description":"Product name and description"},{"name":"market","description":"Target audience and market"},{"name":"date","description":"Target launch date"},{"name":"budget","description":"Marketing budget"},{"name":"uvp","description":"What makes this product unique"}]'::jsonb,
  NULL,
  'Advanced',
  234,
  true,
  '2025-01-14'::timestamptz
),
-- 6. landing-page-copywriter
(
  'landing-page-copywriter',
  'High-Converting Landing Page Copy',
  'Write landing page copy that converts visitors into customers using proven frameworks.',
  '90bbde45-1b2e-498e-8336-268e4fe15bb1',
  'Marketing',
  'marketing',
  E'You are a conversion copywriter specializing in landing pages. Write copy for this page.\n\n**Product/Service:** {{product}}\n**Target Visitor:** {{visitor}}\n**Primary Goal:** {{goal}}\n**Price Point:** {{price}}\n\nWrite complete landing page copy:\n\n1. **Above the Fold**\n   - Headline (benefit-driven, under 10 words)\n   - Subheadline (clarify the offer)\n   - CTA button text\n   - Hero image/video description\n\n2. **Social Proof Section**\n   - Testimonial prompts\n   - Stats/numbers to highlight\n   - Logo bar suggestions\n\n3. **Features \u2192 Benefits**\n   - 3-5 features translated to benefits\n   - Supporting copy for each\n\n4. **Objection Handling**\n   - FAQ section (5 questions)\n   - Risk reversal (guarantee copy)\n   - Trust signals\n\n5. **Final CTA Section**\n   - Urgency/scarcity element\n   - Final benefit summary\n   - CTA with supporting text\n\nOptimize for a conversion rate above 5%.',
  ARRAY['landing-page', 'copywriting', 'conversion', 'cro'],
  'GPT-4o',
  'openai',
  ARRAY['Building landing pages', 'Improving conversion rates', 'Product page optimization'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"product","description":"What you''re selling"},{"name":"visitor","description":"Who lands on this page"},{"name":"goal","description":"Sign up, purchase, book demo"},{"name":"price","description":"Price point or pricing model"}]'::jsonb,
  NULL,
  'Intermediate',
  312,
  true,
  '2025-02-02'::timestamptz
),
-- 7. seo-content-strategy
(
  'seo-content-strategy',
  'SEO Content Strategy Builder',
  'Build a data-driven SEO content strategy with keyword clusters, content calendar, and ranking roadmap.',
  '90bbde45-1b2e-498e-8336-268e4fe15bb1',
  'Marketing',
  'marketing',
  E'You are an SEO strategist. Build a content strategy to rank for the following topic.\n\n**Niche/Industry:** {{industry}}\n**Main topic:** {{topic}}\n**Current domain authority:** {{da}}\n**Competitors:** {{competitors}}\n\nDeliver:\n\n1. **Keyword Research**\n   - Primary keywords (5) with estimated difficulty\n   - Long-tail keywords (15) for quick wins\n   - Question keywords (10) for featured snippets\n   - Keyword clusters organized by topic\n\n2. **Content Plan** (3 months)\n   - Pillar content (2-3 comprehensive guides)\n   - Supporting articles (10-15)\n   - Internal linking strategy\n   - Content gap analysis vs competitors\n\n3. **On-Page SEO Template**\n   - Title tag formula\n   - Meta description template\n   - H1-H3 hierarchy structure\n   - Schema markup recommendations\n\n4. **Technical SEO Checklist**\n   - Site speed items\n   - Mobile optimization\n   - Core Web Vitals focus areas',
  ARRAY['seo', 'content-strategy', 'keywords', 'organic-growth'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Building organic traffic', 'Content marketing strategy', 'Competitive SEO analysis'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"industry","description":"Your industry or niche"},{"name":"topic","description":"Main topic to rank for"},{"name":"da","description":"Domain authority (1-100)"},{"name":"competitors","description":"Top 3 competitor domains"}]'::jsonb,
  NULL,
  'Intermediate',
  256,
  true,
  '2025-01-30'::timestamptz
),
-- 8. ad-creative-generator
(
  'ad-creative-generator',
  'Ad Creative Generator',
  'Generate high-performing ad creatives for Meta, Google, and LinkedIn with copy variations and targeting.',
  '90bbde45-1b2e-498e-8336-268e4fe15bb1',
  'Marketing',
  'marketing',
  E'You are a performance marketing specialist. Create ad creatives for a campaign.\n\n**Platform:** {{platform}}\n**Product/Service:** {{product}}\n**Campaign Objective:** {{objective}}\n**Target Audience:** {{audience}}\n**Budget:** {{budget}}\n\nGenerate:\n\n1. **Ad Copy Variations** (5 per format)\n   - Headlines (30 char limit for Google, longer for Meta)\n   - Primary text / descriptions\n   - CTA options\n\n2. **Visual Concepts** (3 ideas)\n   - Image/video description\n   - Text overlay suggestions\n   - Color and mood direction\n\n3. **Audience Targeting**\n   - Interest targeting\n   - Lookalike suggestions\n   - Exclusions to add\n   - Retargeting segments\n\n4. **A/B Testing Plan**\n   - Variables to test\n   - Budget split recommendation\n   - Statistical significance calculator settings\n\n5. **Performance Projections**\n   - Expected CPM/CPC ranges\n   - Conversion benchmarks for industry',
  ARRAY['advertising', 'paid-media', 'meta-ads', 'google-ads'],
  'GPT-4o',
  'openai',
  ARRAY['Running paid campaigns', 'Creating ad variations', 'Testing ad performance'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"platform","description":"Meta, Google, LinkedIn, TikTok"},{"name":"product","description":"What you''re advertising"},{"name":"objective","description":"Awareness, traffic, conversions"},{"name":"audience","description":"Target demographic and psychographic"},{"name":"budget","description":"Daily or total campaign budget"}]'::jsonb,
  NULL,
  'Intermediate',
  198,
  true,
  '2025-02-06'::timestamptz
);
