-- Batch 1: Software Engineering (6 prompts) + Writing & Content (5 prompts) = 11 prompts
INSERT INTO public.prompts (
  slug,
  title,
  description,
  category_id,
  category_name,
  category_slug,
  prompt,
  tags,
  recommended_model,
  model_icon,
  use_cases,
  example_output,
  output_screenshots,
  "references",
  variables,
  tips,
  difficulty,
  saves_count,
  is_published,
  created_at
) VALUES
-- 1. senior-developer-code-review
(
  'senior-developer-code-review',
  'Senior Developer Code Review',
  'Get a thorough code review from an experienced senior developer perspective, covering correctness, performance, security, and maintainability.',
  '2e6d07b2-776c-484d-a21d-b20d061f30cb',
  'Software Engineering',
  'software-engineering',
  E'You are a senior software engineer with 15+ years of experience conducting a thorough code review. Review the following code with extreme attention to detail.\n\n**Code to Review:**\n```{{language}}\n{{code}}\n```\n\n**Context:** {{context}}\n\nPlease provide your review covering:\n\n1. **Correctness** - Are there any bugs, edge cases, or logic errors?\n2. **Performance** - Any performance bottlenecks or optimization opportunities?\n3. **Security** - Any security vulnerabilities (injection, XSS, auth issues)?\n4. **Maintainability** - Is the code readable, well-structured, and following best practices?\n5. **Testing** - What test cases should be written for this code?\n\nFor each issue found, provide:\n- Severity: \U0001F534 Critical / \U0001F7E1 Warning / \U0001F535 Suggestion\n- Line reference\n- Explanation of the issue\n- Suggested fix with code example\n\nEnd with an overall assessment and a quality score out of 10.',
  ARRAY['code-review', 'debugging', 'best-practices', 'security'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Pre-merge code reviews', 'Learning best practices', 'Finding security vulnerabilities', 'Improving code quality'],
  NULL,
  NULL,
  '[{"title":"Google Engineering Practices - Code Review","url":"https://google.github.io/eng-practices/review/"}]'::jsonb,
  '[{"name":"language","description":"Programming language (e.g., Python, TypeScript)"},{"name":"code","description":"The code to review"},{"name":"context","description":"What this code does and where it''s used"}]'::jsonb,
  ARRAY['Include the full function or module for better context', 'Mention the framework being used (React, Django, etc.)', 'Specify any performance constraints or requirements'],
  'Intermediate',
  342,
  true,
  '2025-01-15'::timestamptz
),
-- 2. system-architecture-designer
(
  'system-architecture-designer',
  'System Architecture Designer',
  'Design scalable system architectures with detailed component diagrams, trade-off analysis, and implementation roadmaps.',
  '2e6d07b2-776c-484d-a21d-b20d061f30cb',
  'Software Engineering',
  'software-engineering',
  E'You are a principal systems architect. Design a comprehensive system architecture for the following:\n\n**System:** {{system_description}}\n**Scale:** {{expected_scale}}\n**Constraints:** {{constraints}}\n\nProvide:\n\n1. **High-Level Architecture**\n   - System components and their responsibilities\n   - Data flow between components\n   - ASCII diagram of the architecture\n\n2. **Technology Stack Recommendations**\n   - Database choices with justification\n   - Message queues / event systems\n   - Caching strategy\n   - API design (REST/GraphQL/gRPC)\n\n3. **Scalability Plan**\n   - Horizontal vs vertical scaling strategies\n   - Bottleneck identification\n   - CDN and edge computing considerations\n\n4. **Trade-offs Analysis**\n   - CAP theorem considerations\n   - Consistency vs availability decisions\n   - Cost vs performance trade-offs\n\n5. **Implementation Roadmap**\n   - Phase 1: MVP\n   - Phase 2: Scale\n   - Phase 3: Optimization',
  ARRAY['architecture', 'system-design', 'scalability', 'infrastructure'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Designing new systems from scratch', 'Preparing for system design interviews', 'Scaling existing architectures', 'Technical documentation'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"system_description","description":"What the system needs to do"},{"name":"expected_scale","description":"Users, requests/sec, data volume"},{"name":"constraints","description":"Budget, timeline, team size, existing tech"}]'::jsonb,
  ARRAY['Be specific about expected traffic patterns', 'Mention any existing infrastructure or constraints', 'Include non-functional requirements like latency targets'],
  'Advanced',
  289,
  true,
  '2025-02-01'::timestamptz
),
-- 3. debug-detective
(
  'debug-detective',
  'Debug Detective',
  'Systematically debug complex issues by analyzing error messages, stack traces, and code behavior with a structured approach.',
  '2e6d07b2-776c-484d-a21d-b20d061f30cb',
  'Software Engineering',
  'software-engineering',
  E'You are an expert debugging specialist. Help me systematically debug this issue.\n\n**Error/Symptom:** {{error_description}}\n\n**Stack Trace (if available):**\n```\n{{stack_trace}}\n```\n\n**Relevant Code:**\n```{{language}}\n{{code}}\n```\n\n**Environment:** {{environment}}\n**What I''ve already tried:** {{attempted_fixes}}\n\nPlease follow this debugging methodology:\n\n1. **Error Analysis** - What does the error actually mean?\n2. **Root Cause Hypotheses** - List 3-5 possible root causes ranked by likelihood\n3. **Diagnostic Steps** - What to check to confirm each hypothesis\n4. **Solution** - For the most likely cause, provide a fix with explanation\n5. **Prevention** - How to prevent this class of error in the future',
  ARRAY['debugging', 'troubleshooting', 'error-handling'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Debugging production issues', 'Understanding cryptic error messages', 'Learning systematic debugging'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"error_description","description":"The error message or unexpected behavior"},{"name":"stack_trace","description":"Full stack trace if available"},{"name":"language","description":"Programming language"},{"name":"code","description":"Relevant code that''s failing"},{"name":"environment","description":"OS, runtime version, dependencies"},{"name":"attempted_fixes","description":"What you''ve already tried"}]'::jsonb,
  NULL,
  'Intermediate',
  267,
  true,
  '2025-01-20'::timestamptz
),
-- 4. api-endpoint-generator
(
  'api-endpoint-generator',
  'REST API Endpoint Generator',
  'Generate complete REST API endpoints with validation, error handling, types, and tests.',
  '2e6d07b2-776c-484d-a21d-b20d061f30cb',
  'Software Engineering',
  'software-engineering',
  E'You are a backend API specialist. Generate a complete REST API endpoint implementation.\n\n**Resource:** {{resource_name}}\n**Framework:** {{framework}}\n**Database:** {{database}}\n**Operations needed:** {{operations}}\n\nFor each endpoint, provide:\n\n1. **Route definition** with proper HTTP methods\n2. **Request validation** schema (body, params, query)\n3. **Controller logic** with proper error handling\n4. **Database query/model** code\n5. **Response format** with status codes\n6. **TypeScript/type definitions**\n7. **Unit test** for the endpoint\n8. **API documentation** (OpenAPI/Swagger format)\n\nFollow these best practices:\n- Proper HTTP status codes (201 for creation, 204 for deletion, etc.)\n- Input sanitization and validation\n- Pagination for list endpoints\n- Proper error messages (never expose internal details)\n- Rate limiting considerations',
  ARRAY['api', 'backend', 'rest', 'typescript'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Building new APIs quickly', 'Standardizing API patterns', 'Learning API best practices'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"resource_name","description":"e.g., User, Product, Order"},{"name":"framework","description":"e.g., Express, FastAPI, NestJS"},{"name":"database","description":"e.g., PostgreSQL, MongoDB"},{"name":"operations","description":"e.g., CRUD, search, bulk operations"}]'::jsonb,
  NULL,
  'Intermediate',
  198,
  true,
  '2025-02-05'::timestamptz
),
-- 5. git-commit-message-pro
(
  'git-commit-message-pro',
  'Git Commit Message Pro',
  'Generate clear, conventional commit messages that tell the story of your changes.',
  '2e6d07b2-776c-484d-a21d-b20d061f30cb',
  'Software Engineering',
  'software-engineering',
  E'Analyze the following code changes and generate a professional git commit message following the Conventional Commits specification.\n\n**Diff/Changes:**\n```\n{{diff}}\n```\n\n**Additional context:** {{context}}\n\nGenerate:\n1. A commit message following this format:\n   `type(scope): subject`\n\n   Body explaining what and why (not how).\n\n   Footer with breaking changes or issue references.\n\n2. Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore\n3. Keep subject under 50 characters\n4. Wrap body at 72 characters\n5. If multiple logical changes, suggest splitting into separate commits',
  ARRAY['git', 'workflow', 'collaboration'],
  'Claude Haiku 3.5',
  'anthropic',
  ARRAY['Writing clear commit messages', 'Maintaining clean git history', 'Following team conventions'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"diff","description":"The git diff or description of changes"},{"name":"context","description":"Why the change was made, related issue"}]'::jsonb,
  NULL,
  'Beginner',
  156,
  true,
  '2025-01-10'::timestamptz
),
-- 6. test-case-generator
(
  'test-case-generator',
  'Comprehensive Test Case Generator',
  'Generate thorough test suites covering happy paths, edge cases, error scenarios, and integration tests.',
  '2e6d07b2-776c-484d-a21d-b20d061f30cb',
  'Software Engineering',
  'software-engineering',
  E'You are a QA engineer and testing specialist. Generate a comprehensive test suite for the following code.\n\n**Code to test:**\n```{{language}}\n{{code}}\n```\n\n**Testing framework:** {{framework}}\n**Type of tests needed:** {{test_types}}\n\nGenerate tests covering:\n\n1. **Happy Path Tests** - Normal expected behavior\n2. **Edge Cases** - Boundary values, empty inputs, max values\n3. **Error Cases** - Invalid inputs, network failures, timeouts\n4. **Integration Tests** - How this interacts with other components\n5. **Performance Tests** - If applicable\n\nFor each test:\n- Clear, descriptive test name (it should "do X when Y")\n- Arrange-Act-Assert pattern\n- Proper mocking of dependencies\n- Comments explaining what each test validates\n\nAlso provide:\n- Test coverage summary\n- Any untestable parts and suggestions to make them testable',
  ARRAY['testing', 'qa', 'tdd', 'unit-tests'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Writing comprehensive test suites', 'Improving test coverage', 'Learning testing best practices'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"language","description":"Programming language"},{"name":"code","description":"The code to generate tests for"},{"name":"framework","description":"e.g., Jest, Pytest, JUnit"},{"name":"test_types","description":"Unit, integration, e2e, or all"}]'::jsonb,
  NULL,
  'Intermediate',
  213,
  true,
  '2025-01-25'::timestamptz
),
-- 7. blog-post-architect
(
  'blog-post-architect',
  'Blog Post Architect',
  'Create SEO-optimized, engaging blog posts with structured outlines, compelling hooks, and strategic keyword placement.',
  '985c1952-2f92-47fb-8e01-b0632098d960',
  'Writing & Content',
  'writing-content',
  E'You are an expert content strategist and SEO specialist. Create a comprehensive blog post.\n\n**Topic:** {{topic}}\n**Target Keyword:** {{keyword}}\n**Target Audience:** {{audience}}\n**Word Count:** {{word_count}}\n**Tone:** {{tone}}\n\nDeliver:\n\n1. **5 Headline Options** (with power words and numbers)\n2. **Meta Description** (155 characters, includes keyword)\n3. **Blog Post Structure:**\n   - Hook introduction (story, statistic, or question)\n   - H2/H3 subheading hierarchy\n   - Key points for each section\n   - Data points or examples to include\n   - Internal linking opportunities\n   - Call-to-action conclusion\n\n4. **SEO Checklist:**\n   - Primary keyword placement (title, first 100 words, H2s)\n   - Secondary keyword suggestions\n   - Image alt text suggestions\n   - Schema markup recommendations\n\n5. **Full Draft** following the structure above',
  ARRAY['blog', 'seo', 'content-writing', 'marketing'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Creating blog content at scale', 'SEO-optimized article writing', 'Content strategy planning'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"topic","description":"The blog post topic"},{"name":"keyword","description":"Primary SEO target keyword"},{"name":"audience","description":"Who is this for?"},{"name":"word_count","description":"Target length (e.g., 1500)"},{"name":"tone","description":"Professional, casual, authoritative, etc."}]'::jsonb,
  NULL,
  'Intermediate',
  445,
  true,
  '2025-01-12'::timestamptz
),
-- 8. viral-twitter-thread
(
  'viral-twitter-thread',
  'Viral Twitter/X Thread Creator',
  'Craft engaging Twitter threads that hook readers and drive engagement using proven viral patterns.',
  '985c1952-2f92-47fb-8e01-b0632098d960',
  'Writing & Content',
  'writing-content',
  E'You are a social media expert who has studied viral Twitter threads. Create a compelling thread.\n\n**Topic:** {{topic}}\n**Key Message:** {{key_message}}\n**Target Audience:** {{audience}}\n**Thread Length:** {{length}} tweets\n\nStructure:\n1. **Hook Tweet** - Stop the scroll. Use one of these patterns:\n   - Contrarian take: "Most people think X. They''re wrong."\n   - Promise: "I spent 100 hours studying X. Here''s what I learned:"\n   - Story: Start with a vivid moment\n\n2. **Body Tweets** (one idea per tweet):\n   - Each tweet should stand alone AND connect to the next\n   - Use short sentences and line breaks\n   - Include specific numbers and examples\n   - Add "tweet 3 is the game-changer" style teasers\n\n3. **Closing Tweet:**\n   - Summarize key takeaway\n   - Clear CTA (follow, retweet, reply)\n   - Link to resource if applicable\n\n4. **Engagement Boosters:**\n   - Reply tweet suggestions\n   - Quote tweet bait\n   - Poll ideas\n\nFormat each tweet with character count.',
  ARRAY['twitter', 'social-media', 'viral-content', 'threads'],
  'GPT-4o',
  'openai',
  ARRAY['Building audience on Twitter/X', 'Content marketing', 'Thought leadership'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"topic","description":"What the thread is about"},{"name":"key_message","description":"The core insight to share"},{"name":"audience","description":"Who should engage with this"},{"name":"length","description":"Number of tweets (5-15)"}]'::jsonb,
  NULL,
  'Beginner',
  367,
  true,
  '2025-02-08'::timestamptz
),
-- 9. email-copywriter
(
  'email-copywriter',
  'High-Converting Email Copywriter',
  'Write emails that get opened, read, and clicked with proven copywriting frameworks.',
  '985c1952-2f92-47fb-8e01-b0632098d960',
  'Writing & Content',
  'writing-content',
  E'You are a direct-response copywriter specializing in email marketing. Write a high-converting email.\n\n**Purpose:** {{purpose}}\n**Product/Service:** {{product}}\n**Target Audience:** {{audience}}\n**Desired Action:** {{cta}}\n**Brand Voice:** {{voice}}\n\nDeliver:\n\n1. **3 Subject Line Options** (A/B test ready)\n   - Include open rate optimization tips for each\n\n2. **Preview Text** (35-90 characters)\n\n3. **Email Body** using the {{framework}} framework:\n   - **PAS:** Problem \u2192 Agitation \u2192 Solution\n   - **AIDA:** Attention \u2192 Interest \u2192 Desire \u2192 Action\n   - **BAB:** Before \u2192 After \u2192 Bridge\n\n4. **CTA Button Text** (3 options)\n\n5. **P.S. Line** (often the most-read part)\n\n6. **Optimization Notes:**\n   - Best send time for this audience\n   - Personalization opportunities\n   - Follow-up email suggestion',
  ARRAY['email', 'copywriting', 'conversion', 'marketing'],
  'Claude Sonnet 4',
  'anthropic',
  ARRAY['Email marketing campaigns', 'Sales outreach', 'Newsletter creation', 'Drip sequences'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"purpose","description":"Welcome, promotion, nurture, re-engagement"},{"name":"product","description":"What you''re promoting"},{"name":"audience","description":"Who receives this email"},{"name":"cta","description":"What should the reader do?"},{"name":"voice","description":"Friendly, professional, urgent, etc."},{"name":"framework","description":"PAS, AIDA, or BAB"}]'::jsonb,
  NULL,
  'Intermediate',
  312,
  true,
  '2025-01-18'::timestamptz
),
-- 10. technical-documentation-writer
(
  'technical-documentation-writer',
  'Technical Documentation Writer',
  'Create clear, comprehensive technical documentation that developers actually want to read.',
  '985c1952-2f92-47fb-8e01-b0632098d960',
  'Writing & Content',
  'writing-content',
  E'You are a senior technical writer at a top tech company. Create documentation for the following.\n\n**What to document:** {{subject}}\n**Audience:** {{audience}}\n**Documentation type:** {{doc_type}}\n\nProduce documentation that includes:\n\n1. **Overview** - What is it, why does it exist, when to use it\n2. **Quick Start** - Get running in under 5 minutes\n3. **Core Concepts** - Key terms and mental models\n4. **Step-by-Step Guide** - Detailed walkthrough with code examples\n5. **API Reference** (if applicable) - Parameters, returns, errors\n6. **Examples** - Real-world use cases with complete code\n7. **Troubleshooting** - Common issues and solutions\n8. **FAQ** - Anticipated questions\n\nStyle guide:\n- Use active voice\n- One idea per sentence\n- Code examples for every concept\n- Progressive disclosure (simple \u2192 complex)\n- Include "Why" not just "How"',
  ARRAY['documentation', 'technical-writing', 'developer-experience'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['API documentation', 'README files', 'Developer guides', 'Internal wikis'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"subject","description":"The API, tool, or system to document"},{"name":"audience","description":"Beginner devs, senior engineers, non-technical"},{"name":"doc_type","description":"API reference, tutorial, guide, README"}]'::jsonb,
  NULL,
  'Intermediate',
  234,
  true,
  '2025-02-10'::timestamptz
),
-- 11. storytelling-framework
(
  'storytelling-framework',
  'Story-Driven Content Framework',
  'Transform any message into a compelling narrative using proven storytelling structures.',
  '985c1952-2f92-47fb-8e01-b0632098d960',
  'Writing & Content',
  'writing-content',
  E'You are a master storyteller and narrative strategist. Transform this message into a compelling story.\n\n**Core Message:** {{message}}\n**Medium:** {{medium}}\n**Audience:** {{audience}}\n**Emotional Goal:** {{emotion}}\n\nUse the following storytelling framework:\n\n1. **The Hook** - An unexpected opening that creates curiosity\n2. **The Setup** - Establish the world, character, and stakes\n3. **The Conflict** - The challenge or problem (make it relatable)\n4. **The Journey** - The struggle and discovery\n5. **The Resolution** - How the challenge was overcome\n6. **The Lesson** - The transferable insight\n7. **The Call** - What the audience should do next\n\nAlso provide:\n- 3 opening line options\n- Sensory details to include\n- Dialogue snippets\n- Emotional arc mapping\n- Where to place the key message for maximum impact',
  ARRAY['storytelling', 'narrative', 'content-strategy', 'engagement'],
  'Claude Opus 4',
  'anthropic',
  ARRAY['Presentations and talks', 'Brand storytelling', 'Case studies', 'Fundraising pitches'],
  NULL,
  NULL,
  '[]'::jsonb,
  '[{"name":"message","description":"The key message or lesson to convey"},{"name":"medium","description":"Blog, presentation, video, podcast"},{"name":"audience","description":"Who you''re telling the story to"},{"name":"emotion","description":"Inspired, motivated, empathetic, curious"}]'::jsonb,
  NULL,
  'Advanced',
  189,
  true,
  '2025-02-12'::timestamptz
);
